### ISSUE TITLE
Recipes-App To-Do List 

### ISSUE THREAD

**Issue by aalrashaid** [aalrashaid/Recipes-App#2]
The To Do List for Base   startup App fro stage Develop:
- [ ] sessions
- [ ] notifications
- [ ] cuisines
- [ ] categories
- [ ] Thumbnails
- [ ] recipes
- [ ] profiles
- [ ] UI and UX
- [ ] sass
- [ ] published book
- [ ] likes
- [ ] Add all ingredients to shopping list
- [ ] Ratings
- [ ] Reviews
- [ ] youtube
- [ ] followers & following
- [ ] Tags
- [ ] hash
- [ ] Recipe nutrition calculator
- [ ] Measurements
