### ISSUE TITLE
 Recipes-App To-Do List Advance 

### ISSUE THREAD

**Issue by aalrashaid** [aalrashaid/Recipes-App#3]
This To Do List  Advance:
- [ ] php artisan session:table 
- [ ] php artisan notifications:table 
- [ ] php artisan queue:batches-table 
- [ ] php artisan queue:table
